### ISSUE TITLE
MunkiOptionalReceiptEditor.py - pkginfo_repo_path not required when no items imported to Munki

### ISSUE THREAD

**Issue by camguise** [autopkg/autopkg#829] opened 2022-09-22 02:03 UTC
This new processor worked great for me yesterday but has unfortunately grown an error today. It appears that MunkiOptionalReceiptEditor.py is expecting there to always be a value set for pkginfo_repo_path passed from a MunkiImporter processor but this value would be empty if no new items need to be imported into Munki. It worked yesterday because there was a new version of Drive available but there isn't today so I'm receiving an error.

I can see from line 34 (link below) that this processors throw an error when pkginfo_repo_path is empty whereas the original custom processor by Sam Keeley just displayed an output message and then a return statement when the repo path is empty. I've linked the equivalent line in the original processor for reference too.

https://github.com/autopkg/autopkg/blob/6f93009e7f7d6db350dbfa911f55e31544d3b0e9/Code/autopkglib/MunkiOptionalReceiptEditor.py#L34

https://github.com/autopkg/keeleysam-recipes/blob/5be0da75953c04f2a6f1a53f7d491f9558185f7e/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py#L31

**Comment by nmcspadden** [comment] 2022-09-24 19:22
This is a dupe of #827

**Closed by nmcspadden** 2022-09-24 19:22 UTC
