### ISSUE TITLE
MunkiTools was updated and PyObjC is no longer compatible

### ISSUE THREAD

**Issue by zenopopovici** [autopkg/autopkg#775] opened 2021-11-16 09:54 UTC
MunkiTools was updated and PyObjC is no longer compatible

**AutoPkg output**
```bash
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 16, in __init__
    from munkilib.admin import munkiimportlib
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 34, in <module>
    from .. import osinstaller
  File "/usr/local/munki/munkilib/osinstaller.py", line 47, in <module>
    from . import info
  File "/usr/local/munki/munkilib/info.py", line 37, in <module>
    import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 18, in <module>
    "/System/Library/Frameworks/CoreServices.framework/CoreServices"
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 136, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 130, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 98, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 292, in main
    self.env["force_munki_repo_lib"],
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 168, in _fetch_repo_library
    munki_repo, munki_repo_plugin, munkilib_dir, repo_subdirectory
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 20, in __init__
    f"munkilib import error: {str(err)}\nMunki tools version 3.2.0.3462 or "
autopkglib.ProcessorError: munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
Failed.
Receipt written to /Users/Zeno/Library/AutoPkg/Cache/com.graffino.autopkg.munki.fig/receipts/Fig.munki-receipt-20211115-174902.plist

The following recipes failed:
    Fig.munki.recipe
        Error in com.graffino.autopkg.munki.fig: Processor: MunkiImporter: Error: munkilib import error: Framework CoreServices could not be found
        Munki tools version 3.2.0.3462 or later is required.
```
**Expected behavior**
Import should be working. Reported bug: https://github.com/munki/munki/issues/1121
 
**Version (please complete the following information):**
 - OS version: 12.0.1
- AutoPkg Version: 2.3.1

**Comment by nmcspadden** [comment] 2021-11-16 12:31
I can't reproduce this.

I just installed Munki 5.6.2, AutoPkg 2.3.1, on macOS 12.1 Beta, and was able to import Google Chrome fine:
```
...
MunkiImporter
{'Input': {'MUNKI_REPO': '/Users/Shared/munki',
           'pkg_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg',
           'pkginfo': {'catalogs': ['testing'],
                       'description': 'Chrome is a fast, simple, and secure '
                                      'web browser, built for the modern web.',
                       'display_name': 'Google Chrome',
                       'name': 'GoogleChrome',
                       'unattended_install': True},
           'repo_subdirectory': 'apps'}}
MunkiImporter: No value supplied for MUNKI_REPO_PLUGIN, setting default value of: FileRepo
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Users/Shared/munki
MunkiImporter: Copied pkginfo to: /Users/Shared/munki/pkgsinfo/apps/GoogleChrome-96.0.4664.45.plist
MunkiImporter:            pkg to: /Users/Shared/munki/pkgs/apps/GoogleChrome-96.0.4664.45.dmg
{'Output': {'munki_importer_summary_result': {'data': {'catalogs': 'testing',
                                                       'icon_repo_path': '',
                                                       'name': 'GoogleChrome',
                                                       'pkg_repo_path': 'apps/GoogleChrome-96.0.4664.45.dmg',
                                                       'pkginfo_path': 'apps/GoogleChrome-96.0.4664.45.plist',
                                                       'version': '96.0.4664.45'},
                                              'report_fields': ['name',
                                                                'version',
                                                                'catalogs',
                                                                'pkginfo_path',
                                                                'pkg_repo_path',
                                                                'icon_repo_path'],
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'imported into '
                                                              'Munki:'},
            'munki_info': {'_metadata': {'created_by': 'nmcspadden',
                                         'creation_date': datetime.datetime(2021, 11, 16, 12, 27, 44),
                                         'munki_version': '5.6.2.4398',
                                         'os_version': '12.1'},
                           'autoremove': False,
                           'catalogs': ['testing'],
                           'description': 'Chrome is a fast, simple, and '
                                          'secure web browser, built for the '
                                          'modern web.',
                           'display_name': 'Google Chrome',
                           'installer_item_hash': '242adb94c90f851b1497a463e15ef3ef6a0dcb023f36ccf035d3f0e1a1bec308',
                           'installer_item_location': 'apps/GoogleChrome-96.0.4664.45.dmg',
                           'installer_item_size': 189018,
                           'installer_type': 'copy_from_dmg',
                           'installs': [{'CFBundleIdentifier': 'com.google.Chrome',
                                         'CFBundleName': 'Chrome',
                                         'CFBundleShortVersionString': '96.0.4664.45',
                                         'CFBundleVersion': '4664.45',
                                         'minosversion': '10.11.0',
                                         'path': '/Applications/Google '
                                                 'Chrome.app',
                                         'type': 'application',
                                         'version_comparison_key': 'CFBundleShortVersionString'}],
                           'items_to_copy': [{'destination_path': '/Applications',
                                              'source_item': 'Google '
                                                             'Chrome.app'}],
                           'minimum_os_version': '10.11.0',
                           'name': 'GoogleChrome',
                           'unattended_install': True,
                           'uninstall_method': 'remove_copied_items',
                           'uninstallable': True,
                           'version': '96.0.4664.45'},
            'munki_repo_changed': True,
            'pkg_repo_path': '/Users/Shared/munki/pkgs/apps/GoogleChrome-96.0.4664.45.dmg',
            'pkginfo_repo_path': '/Users/Shared/munki/pkgsinfo/apps/GoogleChrome-96.0.4664.45.plist'}}
{'AUTOPKG_VERSION': '2.3.1',
 'CHECK_FILESIZE_ONLY': False,
 'DOWNLOAD_URL': 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg',
 'MUNKILIB_DIR': '/usr/local/munki',
 'MUNKI_REPO': '/Users/Shared/munki',
 'MUNKI_REPO_PLUGIN': 'FileRepo',
 'MUNKI_REPO_SUBDIR': 'apps',
 'NAME': 'GoogleChrome',
 'PARENT_RECIPES': ['/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome',
 'RECIPE_DIR': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.munki.recipe',
 'RECIPE_REPOS': {'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes'},
                  '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome'],
 'download_changed': True,
 'etag': '"b0182f"',
 'filename': 'GoogleChrome.dmg',
 'force_munki_repo_lib': False,
 'icon_repo_path': '',
 'input_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg/Google '
               'Chrome.app',
 'last_modified': 'Thu, 11 Nov 2021 04:16:30 GMT',
 'munki_importer_summary_result': {'data': {'catalogs': 'testing',
                                            'icon_repo_path': '',
                                            'name': 'GoogleChrome',
                                            'pkg_repo_path': 'apps/GoogleChrome-96.0.4664.45.dmg',
                                            'pkginfo_path': 'apps/GoogleChrome-96.0.4664.45.plist',
                                            'version': '96.0.4664.45'},
                                   'report_fields': ['name',
                                                     'version',
                                                     'catalogs',
                                                     'pkginfo_path',
                                                     'pkg_repo_path',
                                                     'icon_repo_path'],
                                   'summary_text': 'The following new items '
                                                   'were imported into Munki:'},
 'munki_info': {'_metadata': {'created_by': 'nmcspadden',
                              'creation_date': datetime.datetime(2021, 11, 16, 12, 27, 44),
                              'munki_version': '5.6.2.4398',
                              'os_version': '12.1'},
                'autoremove': False,
                'catalogs': ['testing'],
                'description': 'Chrome is a fast, simple, and secure web '
                               'browser, built for the modern web.',
                'display_name': 'Google Chrome',
                'installer_item_hash': '242adb94c90f851b1497a463e15ef3ef6a0dcb023f36ccf035d3f0e1a1bec308',
                'installer_item_location': 'apps/GoogleChrome-96.0.4664.45.dmg',
                'installer_item_size': 189018,
                'installer_type': 'copy_from_dmg',
                'installs': [{'CFBundleIdentifier': 'com.google.Chrome',
                              'CFBundleName': 'Chrome',
                              'CFBundleShortVersionString': '96.0.4664.45',
                              'CFBundleVersion': '4664.45',
                              'minosversion': '10.11.0',
                              'path': '/Applications/Google Chrome.app',
                              'type': 'application',
                              'version_comparison_key': 'CFBundleShortVersionString'}],
                'items_to_copy': [{'destination_path': '/Applications',
                                   'source_item': 'Google Chrome.app'}],
                'minimum_os_version': '10.11.0',
                'name': 'GoogleChrome',
                'unattended_install': True,
                'uninstall_method': 'remove_copied_items',
                'uninstallable': True,
                'version': '96.0.4664.45'},
 'munki_repo_changed': True,
 'pathname': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg',
 'pkg_path': '/Users/Shared/munki/pkgs/apps/GoogleChrome-96.0.4664.45.dmg',
 'pkg_repo_path': '/Users/Shared/munki/pkgs/apps/GoogleChrome-96.0.4664.45.dmg',
 'pkginfo': {'catalogs': ['testing'],
             'description': 'Chrome is a fast, simple, and secure web browser, '
                            'built for the modern web.',
             'display_name': 'Google Chrome',
             'name': 'GoogleChrome',
             'unattended_install': True},
 'pkginfo_repo_path': '/Users/Shared/munki/pkgsinfo/apps/GoogleChrome-96.0.4664.45.plist',
 'prefetch_filename': False,
 'repo_subdirectory': 'apps',
 'requirement': '(identifier "com.google.Chrome" or identifier '
                '"com.google.Chrome.beta" or identifier '
                '"com.google.Chrome.dev" or identifier '
                '"com.google.Chrome.canary") and (certificate leaf = '
                'H"85cee8254216185620ddc8851c7a9fc4dfe120ef" or certificate '
                'leaf = H"c9a99324ca3fcb23dbcc36bd5fd4f9753305130a")',
 'strict_verification': False,
 'url': 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 4}
Receipt written to /Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/receipts/GoogleChrome-receipt-20211116-072744.plist

The following new items were downloaded:
    Download Path                                                                                              
    -------------                                                                                              
    /Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg  

The following new items were imported into Munki:
    Name          Version       Catalogs  Pkginfo Path                          Pkg Repo Path                       Icon Repo Path  
    ----          -------       --------  ------------                          -------------                       --------------  
    GoogleChrome  96.0.4664.45  testing   apps/GoogleChrome-96.0.4664.45.plist  apps/GoogleChrome-96.0.4664.45.dmg                  
nmcspadden@nmcspadden-mbp Shared % autopkg version
2.3.1
```

**Comment by nmcspadden** [comment] 2021-11-16 12:32
I suspect you have an improper install of Munki or mismatched tools.

**Comment by nmcspadden** [comment] 2021-11-16 12:35
I'm also unable to repro this on master. I'm closing this issue because it doesn't seem to be a current problem between AutoPkg and Munki.

**Closed by nmcspadden** 2021-11-16 12:35 UTC

**Comment by zenopopovici** [comment] 2021-11-16 17:32
@nmcspadden The guys at MunkiTools are saying this is an autopkg issue, you're saying it's a botched install (which it isn't). Please can you help pinpoint the issue? This happens after the latest munkitools install. https://github.com/munki/munki/issues/1121

**Comment by zenopopovici** [comment] 2021-11-16 17:33
@nmcspadden Also this is happening on an M1 system.

**Comment by nmcspadden** [comment] 2021-11-17 02:48
I understand what Greg Neagle is telling you. What I am telling you is that I cannot reproduce this on my M1. I installed the latest munki tools package from GitHub releases, and I tried both Autopkg 2.3.1 and running directly off github master, and I cannot reproduce this issue.

I asked around in Slack and no one else has reproduced the issue either.

I'm sorry, but all the signs point to this problem being unique to your machine, and not an inherent one. Unless you can provide me a way to repro this on a fresh machine, I don't actually see any evidence that this is a fundamental issue between Munki and AutoPkg. 

My suspicion, again, is that you have a mismatched package install from the Munki tools, somehow. I would recommend trying to actually fully remove the munki tools packages (i.e. `sudo pkgutil --forget com.googlecode.munki.whatever`) and then reinstall them and see if it persists.

Or find a way to reproduce this on a fresh machine and show me how. I tried various combinations of things I could think of to reasonably recreate version mismatches and none of them triggered this behavior.
