### ISSUE TITLE
3.0.0RC1 fails on Intel devices

### ISSUE THREAD

**Issue by mhrono** [autopkg/autopkg#882] opened 2023-08-23 14:39 UTC
**Describe the problem**
I run AutoPkg in a GitHub Actions hosted runner, which runs on Intel Mac minis. In testing RC1 of v3, attempting to add a repo with `autopkg repo-add` fails with an error about an incorrect architecture within AutoPkg's embedded Python environment.

**Preferences contents**
N/A: This is a new installation with no repos added. The failure occurs on attempting to add the first repo.

**AutoPkg output**
When attempting to `repo-add`:

```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 35, in <module>
    from autopkgcmd import common_parse, gen_common_parser, search_recipes
  File "/Library/AutoPkg/autopkgcmd/__init__.py", line 15, in <module>
    from autopkgcmd.opts import common_parse, gen_common_parser
  File "/Library/AutoPkg/autopkgcmd/opts.py", line 18, in <module>
    from autopkglib import globalPreferences
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1140, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1014, in import_processors
    __import__(__name__ + "." + name, fromlist=[name]), name
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 22, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 26, in <module>
    import github
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/__init__.py", line [58](https://github.com/1debit/ITE/actions/runs/5951928112/job/16142733507#step:10:59), in <module>
    from github import Auth
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/Auth.py", line 29, in <module>
    import jwt
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: dlopen(/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): tried: '/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have (arm[64](https://github.com/1debit/ITE/actions/runs/5951928112/job/16142733507#step:10:65)), need (x86_64)))
```

After discussing with @nmcspadden in `#autopkg`, he requested to uninstall and reinstall the `github` module following a fresh installation. Post install, I ran `/usr/local/autopkg/python -m pip uninstall github; /usr/local/autopkg/python -m pip install github`, which produced the following (seemingly successful) result:

```
WARNING: Skipping github as it is not installed.
Defaulting to user installation because normal site-packages is not writeable
Collecting github
  Downloading github-1.2.7-py3-none-any.whl (15 kB)
Collecting typing-extensions
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1-cp310-cp310-macosx_10_9_x86_64.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.3/575.3 KB 13.0 MB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from aiohttp==3.8.1->github) (21.4.0)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp310-cp310-macosx_10_9_x86_64.whl (29 kB)
Collecting charset-normalizer<3.0,>=2.0
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp310-cp310-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 KB 513.8 kB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.0-cp310-cp310-macosx_10_9_x86_64.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/46.9 KB 241.8 kB/s eta 0:00:00
Requirement already satisfied: idna>=2.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp==3.8.1->github) (3.4)
Installing collected packages: typing-extensions, multidict, frozenlist, charset-normalizer, async-timeout, yarl, aiosignal, aiohttp, github
  WARNING: The script normalizer is installed in '/Users/runner/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed aiohttp-3.8.1 aiosignal-1.3.1 async-timeout-4.0.3 charset-normalizer-2.1.1 frozenlist-1.4.0 github-1.2.7 multidict-6.0.4 typing-extensions-4.7.1 yarl-1.9.2
```

Unfortunately, attempting to add a repo produced a new error:

```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 35, in <module>
    from autopkgcmd import common_parse, gen_common_parser, search_recipes
  File "/Library/AutoPkg/autopkgcmd/__init__.py", line 15, in <module>
    from autopkgcmd.opts import common_parse, gen_common_parser
  File "/Library/AutoPkg/autopkgcmd/opts.py", line 18, in <module>
    from autopkglib import globalPreferences
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1140, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1014, in import_processors
    __import__(__name__ + "." + name, fromlist=[name]), name
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 22, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 49, in <module>
    class GitHubSession:
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 147, in GitHubSession
    def get_repo(self, name_or_id: str) -> github.Repository.Repository:
AttributeError: type object 'Repository' has no attribute 'Repository'
```

**Expected behavior**
I expected `repo-add` to successfully add to my repo list when given a URL. I am not able to do any additional testing with this version until I can add repos.

**Version (please complete the following information):**
- OS version: 12.6.7 (GitHub Actions hosted runner)
- AutoPkg Version: 3.0.0RC1

**Comment by jby** [comment] 2023-08-23 14:46
I uninstalled `PyGithub` and re-installed it as per request [here](https://macadmins.slack.com/archives/C056155B4/p1692800254695589?thread_ts=1692729278.159149&cid=C056155B4), and it seems to have re-installed the arm-version:

```
sudo /usr/local/autopkg/python -m pip install PyGithub
WARNING: The directory '/Users/jonasb/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting PyGithub
  Downloading PyGithub-1.59.1-py3-none-any.whl (342 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.2/342.2 KB 75.4 MB/s eta 0:00:00
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from PyGithub) (2.8.0)
Requirement already satisfied: deprecated in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from PyGithub) (1.2.14)
Requirement already satisfied: pynacl>=1.4.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from PyGithub) (1.5.0)
Requirement already satisfied: requests>=2.14.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from PyGithub) (2.31.0)
Requirement already satisfied: cryptography>=3.4.0 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (41.0.3)
Requirement already satisfied: cffi>=1.4.1 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pynacl>=1.4.0->PyGithub) (1.15.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2.0.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2023.7.22)
Requirement already satisfied: wrapt<2,>=1.10 in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from deprecated->PyGithub) (1.15.0)
Requirement already satisfied: pycparser in /Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.21)
Installing collected packages: PyGithub
Successfully installed PyGithub-1.59.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.2.1; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/local/autopkg/python -m pip install --upgrade pip' command.
```

```
autopkg version
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 35, in <module>
    from autopkgcmd import common_parse, gen_common_parser, search_recipes
  File "/Library/AutoPkg/autopkgcmd/__init__.py", line 15, in <module>
    from autopkgcmd.opts import common_parse, gen_common_parser
  File "/Library/AutoPkg/autopkgcmd/opts.py", line 18, in <module>
    from autopkglib import globalPreferences
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1140, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1014, in import_processors
    __import__(__name__ + "." + name, fromlist=[name]), name
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 22, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 26, in <module>
    import github
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/__init__.py", line 58, in <module>
    from github import Auth
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/Auth.py", line 29, in <module>
    import jwt
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: dlopen(/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): tried: '/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (no such file), '/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
```

**Comment by jazzace** [comment] 2023-08-23 17:19
My failure is just _running_ `autopkg` on an Intel iMac (27-inch, 2020; T2):
```
% autopkg
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 35, in <module>
    from autopkgcmd import common_parse, gen_common_parser, search_recipes
  File "/Library/AutoPkg/autopkgcmd/__init__.py", line 15, in <module>
    from autopkgcmd.opts import common_parse, gen_common_parser
  File "/Library/AutoPkg/autopkgcmd/opts.py", line 18, in <module>
    from autopkglib import globalPreferences
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1140, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1014, in import_processors
    __import__(__name__ + "." + name, fromlist=[name]), name
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 22, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 26, in <module>
    import github
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/__init__.py", line 58, in <module>
    from github import Auth
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/Auth.py", line 29, in <module>
    import jwt
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: dlopen(/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): tried: '/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (no such file), '/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
```
The only variable here is that I launched AutoPkgr to see if it properly reported the version of AutoPkg (it thinks I should "update" to 2.7.2). It also did not think I had any repos loaded. I then went to the command line to run this command.

**Comment by jazzace** [comment] 2023-08-23 18:20
I uninstalled AutoPkg at the system level (i.e., kept user-space directories but nothing else), reinstalled 2.7.2 (which then ran properly again) and then installed 3.0.0RC1 on top. Failure was identical.

**Comment by nmcspadden** [comment] 2023-08-23 18:36
So it seems like the problem is that the cryptography module, which is required for the pygithub module, is not universal and has to be built per-architecture. So the current 3.0.0.RC1 won't work on Intel machines as-is.

I don't quite understand why pip did the wrong thing with uninstalling + reinstalling, since I would've assumed pip would figure out that even though the python is universal, it should pull the Intel arch for that package. That's a weird pip-ism I don't understand.

**Comment by nmcspadden** [comment] 2023-08-23 21:55
I've added two new packages to the current 3.0.0 RC1 release:
https://github.com/autopkg/autopkg/releases/tag/v3.0.0RC1

I've adjusted the new_requirements.txt to avoid binary builds for the pip modules that were reporting as not universal:
https://github.com/autopkg/autopkg/commit/fada7b4f7a667c47013ed38e6030471fe16de566

There is now a Python package which only contains the autopkg Python, and I have tested it to confirm that it's (supposedly) Universal only:
```
% ./python_universal_tester.sh 3.10                                      
Using Python 3.10
All files are universal!
```

There is also a separate AutoPkg package that contains only Autopkg code.

Please test against this new Python package and let me know if that helps.

**Comment by jazzace** [comment] 2023-08-23 23:03
If I install AutoPkg, then Python 3.10.4, the installer fails with the following error:

> This package is incompatible with this version of macOS.
> The package is trying to install content to the system volume. Contact the software manufacturer for assistance.

Running as a standard user, providing admin credentials when prompted, if that makes a difference.

**Comment by nmcspadden** [comment] 2023-08-23 23:13
Well, that's... unexpected.

**Comment by jazzace** [comment] 2023-08-23 23:19
Probably should have posted a second time (like this) rather than editing the original to ensure visibility via email. To repeat:

Found the problem. The package is trying to install Python.framework to `/` rather than `/Library/AutoPkg/Python3`.

**Comment by nmcspadden** [comment] 2023-08-23 23:25
I can't quite fathom why that would be a specific problem - the first package also does that.

Try this package, which sets the destination specifically to the folder instead of /: https://github.com/autopkg/autopkg/releases/download/v3.0.0RC1/AutoPkg-Python-3.10.4-local.pkg

**Comment by jazzace** [comment] 2023-08-23 23:33
That one installs properly.

**Comment by nmcspadden** [comment] 2023-08-23 23:58
I've updated both packages on the releases page. Please try the new ones.

**Comment by nmcspadden** [comment] 2023-08-24 18:45
I think this problem has been solved, so I am closing it. Reopen it if you are still experiencing issues.

**Closed by nmcspadden** 2023-08-24 18:45 UTC
Labels: beta
