### ISSUE TITLE
Repo add request

### ISSUE THREAD

**Issue by almenscorner** [autopkg/autopkg#878] opened 2023-08-20 13:58 UTC
Recipes for Intune using Intune Uploader and the occasional Munki recipe.

[https://github.com/almenscorner/recipes](https://github.com/almenscorner/recipes)

**Comment by almenscorner** [comment] 2023-10-18 08:19
@homebysix any change this repo can be added? :)

**Comment by homebysix** [comment] 2023-10-19 05:19
Hi @almenscorner - Thanks for the reminder. A couple questions before I create this repo:

- Three of the download recipes in your repo seem to be duplicates of those found elsewhere in the AutoPkg org. Duplicate recipes are discouraged in the autopkg org, so if your recipes do something different than the existing public recipes, I'd recommend adding some information to your recipes' descriptions detailing the differences (see [this example](https://github.com/autopkg/MLBZ521-recipes/blob/49c542915b1777ae3c2ffbf8a179cefb34d19299/NoMAD/NoMADLoginAD.jss.recipe#L5-L8)). Otherwise, see if you can use existing recipes as parents for any new ones. List of existing recipes is below:
    - apizz-recipes/AltTab/AltTab.download.recipe
    - valdore86-recipes/Visual Studio Code/VisualStudioCode.download.recipe
    - hjuutilainen-recipes/iTerm2/iTerm2.download.recipe
- Similarly, the Munki recipe for VSCode seems to be a duplicate of this one:
    - valdore86-recipes/Visual Studio Code/VisualStudioCode.munki.recipe

Once those items are cleaned up, I don't see any reason not to get you a repo on the AutoPkg org.

**Comment by almenscorner** [comment] 2023-10-19 09:17
Duplicates has now been cleaned up!

**Comment by homebysix** [comment] 2023-10-20 08:57
Thank you! Repo added: https://github.com/autopkg/almenscorner-recipes

**Closed by homebysix** 2023-10-20 08:57 UTC
