### ISSUE TITLE
Cannot pickle Objective-C objects

### ISSUE THREAD

**Issue by vaarr80** [autopkg/autopkg#577] opened 2019-11-05 21:10 UTC
Getting the following after updating to 1.3:

[ERROR] TypeError: Cannot pickle Objective-C objects

**Comment by homebysix** [comment] 2019-11-05 21:14
Duplicate of #576.

**Closed by homebysix** 2019-11-05 21:14 UTC

**Comment by andy-signifyd** [comment] 2019-11-06 20:43
Thanks for providing a fix!

Did a test run and its working great again!

Take care!
